import type { NavLink } from '../../.vitepress/theme/types'

type NavData = {
  title: string
  items: NavLink[]
}

export const NAV_DATA: NavData[] = [
  {
    title: 'MC公式ウェブサイト',
    items: [
      {
        //icon: 'https://www.minecraft.net/content/dam/minecraftnet/franchise/logos/Homepage_Download-Launcher_Creeper-Logo_500x500.png',
        icon: '/icons/nav/MC官方网站/Minecraft官网.avif',
        title: 'Minecraft公式サイト',
        link: 'https://www.minecraft.net/',
      },
      {
        //icon: 'https://education.minecraft.net/etc.clientlibs/minecraft-edu/clientlibs/clientlib-common/resources/images/favicon/new-apple-icon.png',
        icon: '/icons/nav/MC官方网站/教育版官网.png',
        title: '教育版公式サイト',
        link: 'https://education.minecraft.net/',
      },
      {
        //icon: 'https://mc.163.com/favicon.ico',
        icon: '/icons/nav/MC官方网站/MC中国版官网.ico',
        title: 'MC中国版公式サイト',
        link: 'https://mc.163.com/',
      },
      {
        //icon: 'https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/logos/Homepage_Gameplay-Trailer_MC-OV-logo_300x300.png',
        icon: '/icons/nav/MC官方网站/反馈社区.png',
        title: 'フィードバックコミュニティ',
        desc: 'MCの公式フィードバックコミュニティ',
        link: 'https://feedback.minecraft.net/',
      },
      {
        //icon: 'https://toolb.cn/favicon/bugs.mojang.com',
        icon: '/icons/nav/MC官方网站/Mojang Jira.png',
        title: 'Mojang Jira',
        desc: 'MCの公式バグ報告コミュニティ',
        link: 'https://feedback.minecraft.net/',
      },
      {
        //icon: 'https://mc.163.com/favicon.ico',
        icon: '/icons/nav/MC官方网站/网易版论坛.ico',
        title: 'NetEase版フォーラム',
        desc: '中国版公式フォーラム',
        link: 'https://mc.netease.com/',
      },
    ],
  },
  {
    title: '非公式フォーラム',
    items: [
      {
        //icon: 'https://media.minecraftforum.net/avatars/0/1/635356669593325566.png',
        icon: '/icons/nav/非官方论坛/Minecraft Forum.webp',
        title: 'Minecraft Forum',
        desc: '海外で有名な非公式Minecraftフォーラム',
        link: 'https://www.minecraftforum.net/',
      },
      {
        //icon: 'https://www.minebbs.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/MineBBS.png',
        title: 'MineBBS',
        desc: '国内のマインクラフト中国語フォーラム、主にBedrock Edition',
        link: 'https://www.minebbs.com/',
      },
      {
        //icon: 'https://klpbbs.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/苦力怕论坛.png',
        title: 'クリーパーフォーラム',
        desc: '国内のマインクラフト中国語フォーラム、主にBedrock Edition',
        link: 'https://klpbbs.com/',
      },
      {
        //icon: 'https://www.himcbbs.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/HiMCBBS.png',
        title: 'HiMCBBS',
        desc: '国内のマインクラフト中国語フォーラム、主にJava Edition',
        link: 'https://www.himcbbs.com/',
      },
      {
        //icon: 'https://www.bangbang93.com/favicon.ico',
        icon: '/icons/nav/非官方论坛/Bangbang93论坛.ico',
        title: 'Bangbang93フォーラム',
        desc: '非常に有名なダウンロードソース国内ミラーサイト——BMCLAPI',
        link: 'https://www.bangbang93.com',
      },
      {
        //icon: 'https://mcobs.fun/static/MCOBS1.png',
        icon: '/icons/nav/非官方论坛/mcobs.png',
        title: '黒曜石フォーラム',
        desc: '国内の新興フォーラム、主にJava Edition',
        link: 'https://mcobs.cn/',
      },
    ],
  },
  {
    title: '百科事典',
    items: [
      {
        //icon: 'https://zh.minecraft.wiki/favicon.ico',
        icon: '/icons/nav/百科/中文 Minecraft Wiki.ico',
        title: '中国語 Minecraft Wiki',
        desc: 'Minecraftで最も有名で権威のある非公式百科事典ウェブサイト',
        link: 'https://zh.minecraft.wiki/',
      },
      {
        //icon: 'https://www.digminecraft.com/favicon.ico',
        icon: '/icons/nav/百科/DigMinecraft.ico',
        title: 'DigMinecraft',
        desc: '英語のMC百科事典ウェブサイト',
        link: 'https://www.digminecraft.com/',
      },
      {
        //icon: 'https://www.mcmod.cn/favicon.ico',
        icon: '/icons/nav/百科/MC模组百科.ico',
        title: 'MCMod百科事典',
        desc: '国内で非常に有名なMCMod百科事典ウェブサイト',
        link: 'https://www.mcmod.cn/',
      },
      {
        //icon: '',
        title: 'Wiki.vg',
        desc: '英語のMinecraft開発ドキュメントライブラリ',
        link: 'https://wiki.vg/',
      },
      {
        //icon: 'https://mineplugin.org/images/a/a6/Mineplugin_logo_2.3.png',
        icon: '/icons/nav/百科/Minecraft 插件百科.png',
        title: 'Minecraftプラグイン百科事典',
        desc: '中国語のMCプラグイン百科事典ウェブサイト',
        link: 'https://mineplugin.org/',
      },
      {
        //icon: 'https://static.miraheze.org/mcpkwiki/c/c5/MCPK_logo.png',
        icon: '/icons/nav/百科/Minecraft Parkour Wiki.webp',
        title: 'Minecraft Parkour Wiki',
        desc: 'MCパルクールの知識とプレイヤーの動作メカニズムを記録するwiki',
        link: 'https://www.mcpk.wiki/wiki/Main_Page/zh',
      },
      {
        //icon: 'https://nitwikit.8aka.org/book.png',
        icon: '/icons/nav/百科/笨蛋 MC 开服教程.png',
        title: '初心者MCサーバー開設チュートリアル',
        desc: 'MCサーバー開設チュートリアル',
        link: 'https://nitwikit.8aka.org/',
      },
    ],
  },
  {
    title: 'Bedrock Edition開発ドキュメント',
    items: [
      {
        //icon: 'https://wiki.mcbe-dev.net/w/images/f/f0/Wiki.svg',
        icon: '/icons/nav/基岩版开发文档/MC基岩版开发Wiki.svg',
        title: 'MC Bedrock Edition開発Wiki',
        link: 'https://wiki.mcbe-dev.net/',
      },
      {
        //icon: 'https://wiki.bedrock.dev/assets/images/homepage/wikilogo.png',
        icon: '/icons/nav/基岩版开发文档/Bedrock Wiki.png',
        title: 'Bedrock Wiki',
        link: 'https://wiki.bedrock.dev',
      },
      {
        //icon: 'https://github.com/destruc7i0n/bedrock-dot-dev/blob/master/public/favicon/apple-touch-icon.png?raw=true',
        icon: '/icons/nav/基岩版开发文档/bedrock.dev.png',
        title: 'bedrock.dev',
        link: 'https://bedrock.dev/',
      },
      {
        //icon: 'https://www.microsoft.com/favicon.ico?v2',
        icon: '/icons/nav/基岩版开发文档/MCBE 官方创作者文档.ico',
        title: 'MCBE公式クリエイタードキュメント',
        desc: 'Microsoft公式MCBEクリエイタードキュメント',
        link: 'https://learn.microsoft.com/zh-cn/minecraft/creator/?view=minecraft-bedrock-stable',
      },

    ],
  },
  {
    title: 'リソースサイト',
    items: [
      {
        //icon: 'https://mcversions.net/favicon.ico',
        icon: '/icons/nav/资源站/MCVersions.ico',
        title: 'MCVersions',
        desc: 'Java Edition各バージョンjarダウンロード',
        link: 'https://mcversions.net/',
      },
      {
        //icon: 'https://bbk.endyun.ltd/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft for Android 版本库.ico',
        title: 'Minecraft for Androidバージョンライブラリ',
        desc: 'Android Bedrock Editionダウンロード',
        link: 'https://bbk.endyun.ltd/',
      },
      {
        //icon: 'https://images.mcappx.com/logo/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft for Windows 版本库.ico',
        title: 'Minecraft for Windowsバージョンライブラリ',
        desc: 'PC Bedrock Editionダウンロード',
        link: 'https://www.mcappx.com/',
      },
      {
        //icon: 'https://www.fastmirror.net/favicon.ico',
        icon: '/icons/nav/资源站/无极镜像.ico',
        title: 'FastMirror 無極ミラー',
        desc: '各種MCサーバーコアの高速ダウンロード',
        link: 'https://www.fastmirror.net/#/home',
      },
      {
        //icon: 'https://www.curseforge.com/favicon.ico',
        icon: '/icons/nav/资源站/CurseForge.ico',
        title: 'CurseForge',
        desc: '老舗MCリソースサイト',
        link: 'https://www.curseforge.com/minecraft',
      },
      {
        //icon: 'https://modrinth.com/favicon.ico',
        icon: '/icons/nav/资源站/Modrinth.ico',
        title: 'Modrinth',
        desc: '新興のMinecraftサードパーティリソースサイト',
        link: 'https://modrinth.com',
      },
      {
        //icon: 'https://www.planetminecraft.com/favicon.ico',
        icon: '/icons/nav/资源站/PlanetMinecraft.ico',
        title: 'PlanetMinecraft',
        desc: '比較的有名なMinecraftリソースウェブサイト',
        link: 'https://www.planetminecraft.com/',
      },
      {
        //icon: 'https://www.spigotmc.org/favicon.ico',
        icon: '/icons/nav/资源站/SpigotMc.ico',
        title: 'SpigotMc',
        desc: 'SpigotMcのリソースセクション、多くのプラグインがある',
        link: 'https://www.spigotmc.org/resources/',
      },
      {
        //icon: 'https://hangar.papermc.io/_nuxt/hangar-logo.DNKyJEtq.svg',
        icon: '/icons/nav/资源站/Hanger.svg',
        title: 'Hanger',
        desc: 'papermcが提供するプラグインサイト',
        link: 'https://hangar.papermc.io/',
      },
      {
        //icon: 'https://spongepowered.org/favicon.ico',
        icon: '/icons/nav/资源站/Sponge Ore.ico',
        title: 'Sponge Ore',
        desc: 'Spongeサーバープラグインのダウンロードサイト',
        link: 'https://ore.spongepowered.org/',
      },
      {
        //icon: 'https://mcpedl.com/favicon.ico',
        icon: '/icons/nav/资源站/MCPEDL.ico',
        title: 'MCPEDL',
        desc: 'MC Bedrock Edition専用リソースウェブサイト',
        link: 'https://mcpedl.com/',
      },
      {
        //icon: 'https://www.minecraftyard.com/favicon.ico',
        icon: '/icons/nav/资源站/MinecraftYard.ico',
        title: 'MinecraftYard',
        desc: 'Java Editionのリソースを収録',
        link: 'https://www.minecraftyard.com/',
      },
      {
        //icon: 'https://www.minecraftmods.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Mods.ico',
        title: 'Minecraft Mods',
        desc: 'Java EditionのModリソースを収録',
        link: 'https://www.minecraftmods.com/',
      },
      {
        //icon: 'https://www.minecraftmaps.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Maps.ico',
        title: 'Minecraft Maps',
        desc: 'MCゲームマップ専用リソースウェブサイト',
        link: 'https://www.minecraftmaps.com/',
      },
      {
        //icon: 'https://minecraftshader.com/wp-content/uploads/2023/09/sun-favicon-e1695481883503.png',
        icon: '/icons/nav/资源站/Minecraft Shaders.avif',
        title: 'Minecraft Shaders',
        desc: 'MCのシェーダーパックとリソースパックのリソースを提供',
        link: 'https://minecraftshader.com/',
      },
      {
        //icon: 'https://resourcepack.net/wp-content/themes/rp/assets/images/ico-diamond.png',
        icon: '/icons/nav/资源站/Resourse Packs for Minecraft.png',
        title: 'Resource Packs for Minecraft',
        desc: '主にMCの各種リソースパックリソースを提供',
        link: 'https://resourcepack.net/',
      },
      {
        //icon: 'https://littleskin.cn/favicon.png',
        icon: '/icons/nav/资源站/LittleSkin.png',
        title: 'LittleSkin',
        desc: '国内老舗MCスキンサイト',
        link: 'https://littleskin.cn/',
      },
      {
        //icon: 'https://www.minecraftskins.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Skins.ico',
        title: 'Minecraft Skins',
        desc: '英語のMCスキンリソースウェブサイト',
        link: 'https://www.minecraftskins.com/',
      },
      {
        //icon: 'https://mskins.net/favicon.ico',
        icon: '/icons/nav/资源站/MSkins.ico',
        title: 'MSkins',
        desc: '英語のMCスキンリソースウェブサイト',
        link: 'https://mskins.net/',
      },
      {
        //icon: 'https://www.minecraft-schematics.com/favicon.ico',
        icon: '/icons/nav/资源站/Minecraft Schematics.ico',
        title: 'Minecraft Schematics',
        desc: '英語のMC設計図リソースウェブサイト',
        link: 'https://www.minecraft-schematics.com/',
      },
      {
        icon: '/icons/nav/资源站/Minecraft_Sounds.webp',
        title: 'Minecraft Sounds',
        desc: '国内MCサウンドエフェクトダウンロードウェブサイト',
        link: 'https://o.xbottle.top/mcsounds/',
      },
    ],
  },
  {
    title: 'サーバーポータル',
    items: [
      {
        icon: '/logo.png',
        title: 'MCJPG組織',
        desc: 'MCJPG組織公式サイト',
        link: 'https://mcjpg.org',
      },
      {
        icon: '/icons/nav/服务器门户/MSCPO.webp',
        title: 'MSCPO',
        desc: 'サーバー集合宣伝組織',
        link: 'https://mscpo.top/',
      },
      {
        //icon: 'https://toolb.cn/favicon/minecraftservers.org',
        icon: '/icons/nav/服务器门户/Minecraft Servers.png',
        title: 'Minecraft Servers',
        desc: '海外で比較的有名なサーバーリソースウェブサイト',
        link: 'https://minecraftservers.org/',
      },
      {
        //icon: 'https://minecraft-mp.com/favicon.ico',
        icon: '/icons/nav/服务器门户/Minecraft Multiplayer.ico',
        title: 'Minecraft Multiplayer',
        desc: '海外で比較的有名なサーバーリソースウェブサイト',
        link: 'https://minecraft-mp.com/',
      },
      {
        //icon: 'https://www.mclists.cn/template/images/favicon.ico',
        icon: '/icons/nav/服务器门户/我的世界找服网.ico',
        title: 'マインクラフトサーバー検索サイト',
        desc: '国内のサーバーリソースウェブサイト',
        link: 'https://www.mczfw.cn/',
      },
      {
        //icon: 'https://cdn.mczfw.cn/images/logo.png',
        icon: '/icons/nav/服务器门户/Minecraft服务器列表.png',
        title: 'Minecraftサーバーリスト',
        desc: '国内のサーバーリソースウェブサイト',
        link: 'https://www.mczfw.cn/',
      },
      {
        //icon: 'https://www.mcmod.cn/favicon.ico',
        icon: '/icons/nav/服务器门户/MCMOD服务器列表.ico',
        title: 'MCMODサーバーリスト',
        desc: 'MCMODサーバーセクション',
        link: 'https://play.mcmod.cn/',
      },
    ],
  },
  {
    title: '機能的ウェブサイト',
    items: [
      {
        icon: '/icons/nav/功能性网站/MCICP.ico',
        title: 'MCICP',
        desc: 'MC世界のMCICP仮想登録のパイオニア！',
        link: 'https://www.mcicp.com/',
      },
      {
        //icon: 'https://www.chunkbase.com/favicon.ico',
        icon: '/icons/nav/功能性网站/Chunk Base.ico',
        title: 'Chunk Base',
        desc: 'シード検索器、チャンク検索器などのツールサイト',
        link: 'https://www.chunkbase.com/',
      },
      {
        //icon: 'http://mcid.lingningyu.cn/webIcon_mcid.png',
        icon: '/icons/nav/功能性网站/MCID.png',
        title: 'MCID',
        desc: 'アイテムID検索ウェブサイト',
        link: 'http://mcid.lingningyu.cn/',
      },
      {
        //icon: 'https://minecraft.tools/favicon.ico',
        icon: '/icons/nav/功能性网站/Minecraft Tools.ico',
        title: 'Minecraft Tools',
        desc: '各種カスタマイズツールを提供',
        link: 'https://minecraft.tools/',
      },
      {
        //icon: 'https://mctools.org/img/icon.png',
        icon: '/icons/nav/功能性网站/Minecraft Server Tools.png',
        title: 'Minecraft Server Tools',
        desc: '各種サーバーカスタマイズツールを提供',
        link: 'https://mctools.org/',
      },
      {
        //icon: 'https://mcsrvstat.us/img/minecraft.png',
        icon: '/icons/nav/功能性网站/Minecraft Server Status.png',
        title: 'Minecraft Server Status',
        desc: 'ウェブMCサーバーステータス検出',
        link: 'https://mcsrvstat.us/',
      },
      {
        //icon: 'https://mcstatus.io/favicon.ico',
        icon: '/icons/nav/功能性网站/MCS.ico',
        title: 'MCS',
        desc: 'ウェブMCサーバーステータス検出',
        link: 'https://mcstatus.io/',
      },
      {
        //icon: 'https://mclo.gs/img/favicon.ico',
        icon: '/icons/nav/功能性网站/mclo.gs.ico',
        title: 'mclo.gs',
        desc: 'MCサーバーログ分析',
        link: 'https://mclo.gs/',
      },
      {
        //icon: 'https://redenmc.com/reden_256.png',
        icon: '/icons/nav/功能性网站/Reden.png',
        title: 'Reden',
        desc: 'ワールドイーターなどの設計図ファイルのオンライン生成',
        link: 'https://redenmc.com/',
      },
      {
        //icon: 'https://rebane2001.com/mapartcraft/images/favicon.ico',
        icon: '/icons/nav/功能性网站/MapartCraft.ico',
        title: 'MapartCraft',
        desc: 'MCピクセルアート生成器、設計図対応',
        link: 'https://rebane2001.com/mapartcraft/zh-Hans',
      },
      {
        //icon: 'https://www.minecraftpfp.com/PFP/I_Like_Cats__.png',
        icon: '/icons/nav/功能性网站/Minecraft PFP.png',
        title: 'Minecraft PFP',
        desc: '正規版アカウントスキンからアバターを生成',
        link: 'https://www.minecraftpfp.com/',
      },
      {
        //icon: 'https://www.gamergeeks.net/favicon.ico',
        icon: '/icons/nav/功能性网站/GAMEGEEKS.ico',
        title: 'GAMEGEEKS',
        desc: 'ウェブMCコマンド生成',
        link: 'https://www.gamergeeks.net/',
      },
      {
        //icon: 'https://wallpapers.novaskin.me/apple-touch-icon.png',
        icon: '/icons/nav/功能性网站/Nova Skin.png',
        title: 'Nova Skin',
        desc: 'ウェブMCスキンサイト、スキンの作成・アップロード・壁紙ダウンロード可能',
        link: 'https://minecraft.novaskin.me/',
      },
      {
        //icon: 'https://skin.endyun.ltd/img/favicon.ico',
        icon: '/icons/nav/功能性网站/MC-3D皮肤预览.ico',
        title: 'MC-3Dスキンプレビュー',
        desc: 'MCスキン検索、3Dプレビュー',
        link: 'https://skin.endyun.ltd/',
      },
      {
        //icon: 'https://textcraft.net/favicon.ico',
        icon: '/icons/nav/功能性网站/Textcraft.ico',
        title: 'Textcraft',
        desc: 'MC風の各種アート文字を生成',
        link: 'https://textcraft.net/',
      },
      {
        //icon: 'https://chunker.app/favicon.png',
        icon: '/icons/nav/功能性网站/Chunker.png',
        title: 'Chunker',
        desc: 'オンラインMCクロスバージョンマップコンバーター、JEとBE相互変換対応',
        link: 'https://chunker.app/',
      },
      {
        //icon: 'https://minecraft-heads.com/themes/mch-v2/assets/images/chest.webp',
        icon: '/icons/nav/功能性网站/Minecraft Heads.webp',
        title: 'Minecraft Heads',
        desc: '大量のMC装飾用ヘッドを収集',
        link: 'https://www.minecraft-heads.com/',
      },
      {
        //icon: 'https://minecraftshapes.com/favicon.ico',
        icon: '/icons/nav/功能性网站/Minecraft Shapes.ico',
        title: 'Minecraft Shapes',
        desc: 'MCで規格的な図形を建築する指導',
        link: 'https://minecraftshapes.com/',
      },
      {
        //icon: 'https://zh-cn.namemc.com/favicon.ico',
        icon: '/icons/nav/功能性网站/NameMC.ico',
        title: 'NameMC',
        desc: '正規版プレイヤーのスキン、名前、スキン、UUIDなどの情報を検索',
        link: 'https://zh-cn.namemc.com/',
      },
      {
        //icon: 'https://mcuuid.net/favicon.ico',
        icon: '/icons/nav/功能性网站/Minecraft UUID.ico',
        title: 'Minecraft UUID',
        desc: '正規版プレイヤーのUUIDなどの情報を検索',
        link: 'https://mcuuid.net/',
      },
    ],
  },
  {
    title: 'ModとShaderローダー',
    items: [
      {
        //icon: 'https://forums.minecraftforge.net/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/Forge.ico',
        title: 'Forge',
        desc: '老舗Modローダー公式サイト',
        link: 'https://forums.minecraftforge.net/',
      },
      {
        //icon: 'https://neoforged.net/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/NeoForge.ico',
        title: 'NeoForge',
        desc: 'Forgeの高バージョンでのより良いフォーク',
        link: 'https://neoforged.net/',
      },
      {
        //icon: 'https://fabricmc.net/assets/logo.png',
        icon: '/icons/nav/模组和光影加载器/Fabric.png',
        title: 'Fabric',
        desc: '新興人気Modローダー',
        link: 'https://fabricmc.net/',
      },
      {
        //icon: 'https://quiltmc.org/favicon/favicon-32x32.png',
        icon: '/icons/nav/模组和光影加载器/Quilt.webp',
        title: 'Quilt',
        desc: 'Fabricの下流フォーク',
        link: 'https://quiltmc.org/en/',
      },
      {
        //icon: 'https://www.liteloader.com/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/LiteLoader.ico',
        title: 'LiteLoader',
        desc: '軽量Modローダー、長期間更新されていない',
        link: 'http://www.liteloader.com/',
      },
      {
        //icon: 'https://www.optifine.net/favicon.ico',
        icon: '/icons/nav/模组和光影加载器/Optifine.ico',
        title: 'Optifine',
        desc: '老舗レンダリング最適化Mod高解像度修正、Shaderローダーとしても使用可能',
        link: 'https://www.optifine.net',
      },
      {
        //icon: 'https://cdn.modrinth.com/data/YL57xq9U/dc558eece920db435f9823ce86de0c4cde89800b.png',
        icon: '/icons/nav/模组和光影加载器/Iris Shaders.webp',
        title: 'Iris Shaders',
        desc: 'Fabric駆動のJava Edition高バージョンShaderローダー、Sodiumと互換性あり',
        link: 'https://irisshaders.net/',
      },
    ],
  },
  {
    title: 'ランチャーとクライアント',
    items: [
      {
        //icon: 'https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/img/Launcher_Icon.png',
        icon: '/icons/nav/启动器和客户端/Minecraft 官方启动器.avif',
        title: 'Minecraft 公式ランチャー',
        desc: 'MC公式ランチャー',
        link: 'https://www.minecraft.net/zh-hans/download',
      },
      {
        //icon: 'https://hmcl.huangyuhui.net/favicon.ico',
        icon: '/icons/nav/启动器和客户端/HMCL.ico',
        title: 'HMCL',
        desc: 'クラシック老舗ランチャー、クロスプラットフォーム',
        link: 'https://hmcl.huangyuhui.net/',
      },
      {
        //icon: '/icons/PCL2.png',
        icon: '/icons/nav/启动器和客户端/PCL2.png',
        title: 'PCL2',
        desc: '新興ランチャー、初心者に適している',
        link: 'https://afdian.com/p/0164034c016c11ebafcb52540025c377',

      },
      {
        //icon: 'https://www.bakaxl.com/favicon.ico',
        icon: '/icons/nav/启动器和客户端/BakaXL.ico',
        title: 'BakaXL',
        desc: '国産2次元ランチャー、美しいインターフェース',
        link: 'https://www.bakaxl.com/',
      },
      {
        //icon: 'https://multimc.org/favicon.ico',
        icon: '/icons/nav/启动器和客户端/MultiMC.ico',
        title: 'MultiMC',
        desc: '海外老舗ランチャー、中国語サポート',
        link: 'https://multimc.org/',
      },
      {
        //icon: 'https://mc.163.com/favicon.ico',
        icon: '/icons/nav/启动器和客户端/中国版启动器.ico',
        title: '中国版ランチャー',
        desc: '中国版公式サイト',
        link: 'https://mc.163.com/',
      },
      {
        //icon: 'https://www.lunarclient.com/assets/img/favicon.ico',
        icon: '/icons/nav/启动器和客户端/Lunar Client.ico',
        title: 'Lunar Client',
        desc: '人気PVPクライアント',
        link: 'https://www.lunarclient.com/',
      },
      {
        //icon: 'https://assets.badlion.net/site/favicon.webp',
        icon: '/icons/nav/启动器和客户端/Badlion Client.webp',
        title: 'Badlion Client',
        desc: '人気PVPクライアント',
        link: 'https://client.badlion.net/zh-CN',
      },
      {
        //icon: 'https://labymod.net/page/tpl/assets/images/icons/favicon.ico',
        icon: '/icons/nav/启动器和客户端/Labymod.ico',
        title: 'Labymod',
        desc: '人気PVPクライアント',
        link: 'https://labymod.net/zh_Hans',
      },
      {
        //icon: 'https://feathermc.com/favicon/apple-touch-icon.png',
        icon: '/icons/nav/启动器和客户端/FEATHER CLIENT.png',
        title: 'FEATHER CLIENT',
        desc: '人気PVPクライアント',
        link: 'https://feathermc.com/',
      },
    ],
  },
  {
    title: '実用ソフトウェア',
    items: [
      {
        icon: '/icons/nav/实用软件/EaglerCraft.webp',
        title: 'EaglerCraftX',
        desc: 'ブラウザ版MC バージョンJE1.8.8',
        link: 'https://eaglercraft.ru/',
      },
      {
        //icon: 'https://mccteam.github.io/icons/favicon-32x32.png',
        icon: '/icons/nav/实用软件/MCC.png',
        title: 'MCC',
        desc: 'MCコマンドラインクライアント',
        link: 'https://mccteam.github.io/l10n/zh-Hans/',
      },
      {
        //icon: '/icons/MCA.png',
        icon: '/icons/nav/实用软件/MCA Selector.png',
        title: 'MCA Selector',
        desc: 'MCチャンクセレクター、チャンク編集に便利、中国語対応',
        link: 'https://github.com/Querz/mcaselector',
      },
      {
        //icon: 'https://www.worldpainter.net/favicon.ico',
        icon: '/icons/nav/实用软件/WorldPainter.ico',
        title: 'WorldPainter',
        desc: 'MC地形制作ソフトウェア',
        link: 'https://www.worldpainter.net/',
      },
      {
        //icon: 'https://www.radmin.com/favicon.svg',
        icon: '/icons/nav/实用软件/Radmin LAN.svg',
        title: 'Radmin LAN',
        desc: 'バーチャルLANソフトウェア、マルチプレイに使用可能',
        link: 'https://www.radmin.com/cn/',
      },
      {
        //icon: 'https://www.mineimator.com/images/logo.png',
        icon: '/icons/nav/实用软件/Mine-imator.png',
        title: 'Mine-imator',
        desc: 'MCアニメーション制作ソフトウェア',
        link: 'https://www.mineimator.com/',
      },
      {
        //icon: 'https://mcreator.net/themes/mcreator/favicon.ico',
        icon: '/icons/nav/实用软件/MCreator.ico',
        title: 'MCreator',
        desc: 'ビジュアルMCMod制作ソフトウェア',
        link: 'https://mcreator.net/',
      },
      {
        //icon: 'https://www.blockbench.net/favicon.svg',
        icon: '/icons/nav/实用软件/BlockBench.svg',
        title: 'BlockBench',
        desc: 'MCモデリングソフトウェア',
        link: 'https://www.blockbench.net/',
      },
      {
        //icon: 'https://serverpackcreator.de/icons/favicon-128x128.png',
        icon: '/icons/nav/实用软件/ServerPackCreator.png',
        title: 'ServerPackCreator',
        desc: 'Modサーバーコアを生成',
        link: 'https://serverpackcreator.de/#/',
      },
    ],
  },
]